from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)

from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.enums import TA_CENTER
from reportlab.lib import colors
from reportlab.lib.units import inch

from datetime import datetime



def create_pdf(result):

    filename = "Resume_Analysis_Report.pdf"

    doc = SimpleDocTemplate(filename)

    styles = getSampleStyleSheet()

    story = []


    title_style = styles["Title"]
    title_style.alignment = TA_CENTER
    title_style.textColor = colors.darkblue

    story.append(
        Paragraph(
            "AI Resume Analyzer Report",
            title_style
        )
    )

    story.append(
        Spacer(1, 0.3 * inch)
    )

    today = datetime.now().strftime("%d %B %Y")

    score = result["ats_score"]

    if score >= 80:
        status = "Excellent"

    elif score >= 60:
        status = "Good"

    else:
        status = "Needs Improvement"

    info_data = [
        ["ATS Score", f"{score}%"],
        ["Generated On", today],
        ["Resume Status", status]
    ]

    info_table = Table(info_data, colWidths=[180, 180])

    info_table.setStyle(TableStyle([

        ("BACKGROUND", (0, 0), (1, 0), colors.lightblue),

        ("TEXTCOLOR", (0, 0), (-1, -1), colors.black),

        ("GRID", (0, 0), (-1, -1), 1, colors.grey),

        ("FONTNAME", (0, 0), (-1, -1), "Helvetica-Bold"),

        ("BOTTOMPADDING", (0, 0), (-1, -1), 10),

    ]))

    story.append(info_table)

    story.append(
        Spacer(1, 0.3 * inch)
    )
    


    story.append(
        Spacer(1,0.2*inch)
    )

    story.append(
        Paragraph("<br/><b>MATCHING SKILLS</b>", styles["Heading1"])
    )

    for skill in result["matching_skills"]:
        story.append(
            Paragraph(f"• {skill}", styles["BodyText"])
        )

    story.append(
        Spacer(1,0.2*inch)
    )

    story.append(
        Paragraph("<br/><b>MISSING SKILLS</b>", styles["Heading1"])
    )

    for skill in result["missing_skills"]:
        story.append(
            Paragraph(f"• {skill}", styles["BodyText"])
        )
    
    story.append(
        Spacer(1,0.2*inch)
    )

    story.append(
        Paragraph("<br/><b>STRENGTHS</b>", styles["Heading1"])
    )

    for item in result["strengths"]:
        story.append(
            Paragraph(f"• {item}", styles["BodyText"])
        )

    story.append(
        Spacer(1,0.2*inch)
    )

    story.append(
        Paragraph("<br/><b>WEAKNESSES</b>", styles["Heading1"])
    )

    for item in result["weaknesses"]:
        story.append(
            Paragraph(f"• {item}", styles["BodyText"])
        )

    story.append(
        Spacer(1,0.2*inch)
    )

    story.append(
        Paragraph("<br/><b>SUGGESTIONS</b>", styles["Heading1"])
    )

    for item in result["suggestions"]:
        story.append(
            Paragraph(f"• {item}", styles["BodyText"])
        )
    
    story.append(
        Spacer(1,0.2*inch)
    )

    story.append(
        Paragraph("<br/><b>INTERVIEW QUESTIONS</b>", styles["Heading1"])
    )

    for item in result["interview_questions"]:
        story.append(
            Paragraph(f"• {item}", styles["BodyText"])
        )

    story.append(
        Spacer(1,0.3*inch)
    )

    story.append(
        Paragraph(
            "<hr/>",
            styles["Normal"]
        )
    )

    story.append(
        Paragraph(
            "<b>Generated by AI Resume Analyzer using Gemini AI</b>",
            styles["Italic"]
        )
    )

    story.append(
        Paragraph(
            "Developed by Harshali Panchal",
            styles["Italic"]
        )
    )


    doc.build(story)

    return filename